from PIL import Image
import numpy as np
import matplotlib.pyplot as plt

im = Image.open("jacek.png")

r, g, b, a = im.split()
obraz2 = im.convert('RGB')
# obraz2.show()
# a.show()

obraz3 = Image.new('RGB', im.size, (255, 255, 255))
obraz3.paste(im, (0, 0), a)
obraz3.save("obraz3.png")
# obraz3.show()

czy_rowne = np.array_equal(obraz3, obraz2)
print(czy_rowne)

tryby = ['CMYK', 'YCbCr', 'HSV']
plt.figure(figsize=(16, 16))
i = 1
for t in tryby:
    file_name = "tryb_" + str(t)
    im_c = obraz3.convert(t)
    plt.subplot(1, 3, i)
    plt.title(str(file_name))
    plt.imshow(im_c, "gray")
    plt.axis('off')
    i += 1
plt.savefig("fig1.png")
# plt.show()


obrazhsv = obraz3.convert('HSV')
h, s, v = obrazhsv.split()
plt.figure(figsize=(16, 16))
plt.subplot(1, 3, 1)
plt.title("H")
plt.imshow(h, "gray")
plt.axis("off")
plt.subplot(1, 3, 2)
plt.title("S")
plt.imshow(s, "gray")
plt.axis("off")
plt.subplot(1, 3, 3)
plt.title("V")
plt.imshow(v, "gray")
plt.axis("off")
plt.savefig("hsv.png")
# plt.show()

obrazycbcr = obraz3.convert('YCbCr')
y, c, p = obrazycbcr.split()
plt.figure(figsize=(16, 16))
plt.subplot(1, 3, 1)
plt.title("Y")
plt.imshow(y, "gray")
plt.axis("off")
plt.subplot(1, 3, 2)
plt.title("C")
plt.imshow(c, "gray")
plt.axis("off")
plt.subplot(1, 3, 3)
plt.title("R")
plt.imshow(p, "gray")
plt.axis("off")
plt.savefig("ycbcr.png")
# plt.show()

obrazcmyk = obraz3.convert('CMYK')
c, m, y, k = obrazcmyk.split()
plt.figure(figsize=(16, 16))
plt.subplot(2, 2, 1)
plt.title("C")
plt.imshow(c, "gray")
plt.axis("off")
plt.subplot(2, 2, 2)
plt.title("M")
plt.imshow(m, "gray")
plt.axis("off")
plt.subplot(2, 2, 3)
plt.title("Y")
plt.imshow(y, "gray")
plt.axis("off")
plt.subplot(2, 2, 4)
plt.title("K")
plt.imshow(k, "gray")
plt.axis("off")
plt.savefig("cmyk.png")
# plt.show()

obraz4 = Image.open("obraz4.png")
print(im.size, obraz4.size)
obraz4 = obraz4.resize(im.size, 1)
print(im.size, obraz4.size)

ob4cp = obraz4.copy()
ob4cp.paste(im, (0, 0), a)

imcp = im.copy()
imcp.paste(obraz4, (0, 0), a)

plt.figure(figsize=(16, 16))
plt.subplot(1, 2, 1)
plt.title("im w obraz4")
plt.imshow(ob4cp, "gray")
plt.axis("off")
plt.subplot(1, 2, 2)
plt.title("obraz4 w im")
plt.imshow(imcp, "gray")
plt.axis("off")
plt.savefig("fig2.png")
plt.show()
